/* EN ESTE ARCHIVO ENCONTRARÁS TODOS LOS COMANDOS UTILIZADOS A LO LARGO DE NUESTRO ENTRENAMIENTO.

POR AHORA, TE INVITO A PREPARAR TU AMBIENTE PARA QUE COMIENCES A TRABAJAR.

¡MUCHOS ÉXITOS EN TUS ESTUDIOS! */
